export { default } from './emitter.js'
export { default as Class } from './emitter.js'
export type { Interface as t } from './interface.js'
export * from './after.js'
export * from './emitter.js'
export type { Interface } from './interface.js'
export * from './prelude.js'
